import type { Metadata } from "next";
import "./globals.css";
import { CategoryProvider } from "@/context/category-context";

export const metadata: Metadata = {
  title: "Go Master Roulette",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CategoryProvider>
          {children}
        </CategoryProvider>
      </body>
    </html>
  );
}
